language: c

install:
  - curl -sLo /tmp/mono.gpg http://download.mono-project.com/repo/xamarin.gpg
  - sudo apt-key add /tmp/mono.gpg
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-complete nuget mono-vbnc fsharp libgdiplus=2.10-3
  - mozroots --import --sync --quiet
  - mkdir ~/.config/.mono/keypairs
  - chmod 700 ~/.config/.mono/keypairs

script:
  - ./build.sh Default
  - ./build.sh All
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/37eb77d4883119b07df7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
