language: csharp

sudo: false  # use the new container-based Travis infrastructure 

script:
  - ./build.sh Default
  - ./build.sh All
script: 
  - ./build.sh Default

branches:
  except:
    - gh-pages
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/37eb77d4883119b07df7
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
