version: 4.0.0-aci-{build}

build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet pack -c Release --include-symbols --version-suffix "aci-${env:APPVEYOR_BUILD_NUMBER}"

test: off

artifacts:
  - path: '**\*.nupkg'
  - path: '**\BenchmarkDotNet.Artifacts\**\*.*'
